import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import { _electron as electron } from 'playwright'
import { downloadDefaults } from '../src/main/downloads.ts'

test('下载 UI 源布局：任务状态、菜单、软件设置、模板与即时保存', { timeout: 35000 }, async t => {
 const profile = await mkdtemp(join(tmpdir(), 'moe-download-visual-'))
 const settings = downloadDefaults(join(profile, 'images'))
 const expected = JSON.parse(await readFile('tests/fixtures/wpf-download-layout.json', 'utf8'))
 await writeFile(join(profile, 'downloads.json'), JSON.stringify(settings))
 const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE; delete env.ELECTRON_RENDERER_URL
 let app
 t.after(async () => { if (app) await app.close(); await rm(profile, { recursive:true, force:true }) })
 app = await electron.launch({args:['.', `--user-data-dir=${profile}`], env})
 const page = await app.firstWindow(); await page.waitForLoadState('load')
 await page.waitForFunction(() => document.querySelector('#settings-toggle').onclick !== null)
 await app.evaluate(({nativeTheme}) => {nativeTheme.themeSource='light'})
 await page.locator('#download-toggle').click()
 await page.waitForFunction(() => Math.abs(document.querySelector('#downloads').getBoundingClientRect().width-220)<.1)
 assert.equal(await page.locator('#download-toolbar, #download-empty, dialog, #download-import-file').count(), 0)
 assert.equal(await page.evaluate(() => { const form=document.querySelector('#search-form').getBoundingClientRect(), workspace=document.querySelector('#workspace').getBoundingClientRect(); return form.x+form.width/2-workspace.x }), (1060-2-expected.panelWidth)/2)
 await page.screenshot({path:'artifacts/download-ui-empty.png',animations:'disabled'})
 // Visual fixtures exercise every renderer state, including groups unavailable on Konachan-G.
 const tasks = ['queued','downloading','stopped','failed','success','skip'].map((status,i)=>({
  id:`visual-${i}`, name:`konachan-g ${i+1}.jpg`, path:`/pictures/konachan-g/${i+1}.jpg`, root:'/pictures',
  status, text: {queued:'等待下载',downloading:'正在下载：48%',stopped:'已停止',failed:'下载失败',success:'下载完成',skip:'已存在，跳过'}[status],
  progress:status==='downloading'?48:status==='success'?100:0,loaded:0,total:0,autoRename:false,
  source:{id:i+1,url:'https://konachan.net/example.jpg',referer:'https://konachan.net',detail:'',keyword:'',tags:[]}
 }))
 tasks.push({...tasks[1],id:'visual-group',name:'多张图片',children:[{...tasks[4],id:'child1',name:'group p1.jpg'},{...tasks[3],id:'child2',name:'group p2.jpg'}]})
 await app.evaluate(({BrowserWindow},snapshot)=>BrowserWindow.getAllWindows()[0].webContents.send('moe:downloads-changed',snapshot),{settings,tasks})
 await page.locator('.download-row').nth(6).waitFor()
 await page.locator('.download-row').first().click()
 const selectedIds = () => page.locator('.download-row.selected').evaluateAll(rows=>rows.map(row=>row.dataset.id))
 const modifier = process.platform === 'darwin' ? 'Meta' : 'Control'
 await page.locator('.download-row').nth(2).click({modifiers:[modifier]})
 await page.locator('.download-row').nth(3).click({modifiers:['Shift']})
 assert.deepEqual(await selectedIds(),['visual-2','visual-3'])
 await page.locator('.download-row').nth(4).click({modifiers:['Shift']})
 assert.deepEqual(await selectedIds(),['visual-2','visual-3','visual-4'], '连续 Shift 使用同一个锚点')
 await page.locator('.download-row').first().click({modifiers:[modifier,'Shift']})
 assert.deepEqual(await selectedIds(),['visual-0','visual-1','visual-2','visual-3','visual-4'])
 await page.locator('.download-row').first().click()
 await page.keyboard.press('ArrowDown')
 assert.deepEqual(await selectedIds(),['visual-1'])
 await page.keyboard.press('Shift+ArrowDown')
 assert.deepEqual(await selectedIds(),['visual-1','visual-2'])
 await page.keyboard.press('Shift+ArrowUp')
 assert.deepEqual(await selectedIds(),['visual-1'])
 await page.keyboard.press(`${modifier}+ArrowDown`)
 assert.deepEqual(await selectedIds(),['visual-1'])
 await page.keyboard.press(`${modifier}+Space`)
 assert.deepEqual(await selectedIds(),['visual-1','visual-2'])
 await page.keyboard.press('End');assert.deepEqual(await selectedIds(),['visual-group'])
 await page.keyboard.press('Home');assert.deepEqual(await selectedIds(),['visual-0'])
 await page.keyboard.press('PageDown');assert.deepEqual(await selectedIds(),['visual-group'])
 await page.keyboard.press('PageUp');assert.deepEqual(await selectedIds(),['visual-0'])
 assert.equal(await page.locator('.download-row[tabindex="0"]').count(),1)
 await page.locator('.download-row').first().click()
 const geometry = await page.evaluate(() => {
  const panel=document.querySelector('#downloads').getBoundingClientRect(), rows=[...document.querySelectorAll('.download-row')].map(e=>e.getBoundingClientRect())
  const thumb=document.querySelector('.download-thumbnail').getBoundingClientRect(), columns=getComputedStyle(document.querySelector('.download-row')).gridTemplateColumns.split(' ').map(parseFloat)
  return {panelWidth:panel.width,listInset:rows[0].x-panel.x,rowHeight:rows[0].height,rowGap:rows[1].y-rows[0].bottom,thumbnailSize:thumb.width,thumbnailInset:thumb.x-rows[0].x,columns:columns.slice(0,2),childHeight:document.querySelector('.download-subitem').getBoundingClientRect().height}
 })
 for(const [key,value] of Object.entries(geometry)) assert.deepEqual(value,expected[key],key)
 await page.screenshot({path:'artifacts/download-ui-states.png',animations:'disabled'})
 await page.locator('.download-row').first().click({button:'right'})
 const menu=page.locator('#download-menu')
 assert.deepEqual(await menu.locator('button > span:last-child').allTextContents(),expected.menuLabels)
 assert.equal((await menu.boundingBox()).width,expected.menuContentWidth+2*expected.menuPadding+2*expected.menuBorder)
 assert.equal((await menu.locator('button').first().boundingBox()).height,expected.menuRowHeight)
 assert.equal(await menu.locator('i').count(),9)
 await page.screenshot({path:'artifacts/download-ui-menu.png',animations:'disabled'})
 await page.keyboard.press('Escape')
 await page.locator('#settings-toggle').click()
 const popup=page.locator('#settings-popup'), scroll=page.locator('#settings-scroll'), group=page.locator('#download-settings')
 assert.deepEqual(await popup.locator('legend').allTextContents(),expected.settingsGroups)
 await page.screenshot({path:'artifacts/download-ui-settings-initial.png',animations:'disabled'})
 assert.equal((await scroll.boundingBox()).width,expected.settingsContentWidth)
 assert.equal((await scroll.boundingBox()).height,expected.settingsContentHeight)
 for(const [name,[min,max]] of Object.entries(expected.limits)) {
   assert.equal(await group.locator(`[name=${name}]`).getAttribute('min'),String(min));assert.equal(await group.locator(`[name=${name}]`).getAttribute('max'),String(max))
 }
 assert.equal(await group.locator('[name=firstCount]').isDisabled(),true)
 await group.locator('[name=firstOnly]').check()
 assert.equal(await group.locator('[name=firstCount]').isDisabled(),false)
 await group.locator('[name=firstCount]').fill('3');await group.locator('[name=firstCount]').press('Tab')
 assert.equal(await page.locator('#first-count-text').textContent(),'3')
 const file=group.locator('[name=fileTemplate]')
 await file.fill('image ');await file.evaluate(e=>e.setSelectionRange(6,6))
 await group.locator('[data-template=fileTemplate]').getByRole('button',{name:'作品ID',exact:true}).click()
 assert.equal(await file.inputValue(),'image %id')
 assert.equal(await group.locator('[data-template=fileTemplate] button').count(),13)
 await page.screenshot({path:'artifacts/download-ui-template.png',animations:'disabled'})
 await group.locator('[name=autoRename]').check()
 assert.equal(await group.locator('[data-template=fileTemplate]').isHidden(),true)
 await page.locator('#settings-toggle').click()
 const saved=await page.evaluate(()=>window.moe.downloads())
 assert.equal(saved.settings.fileTemplate,'image %id');assert.equal(saved.settings.firstCount,3);assert.equal(saved.settings.autoRename,true)
 await page.locator('#settings-toggle').click()
 await group.getByRole('button',{name:'恢复默认文件命名格式'}).click()
 assert.equal(await file.inputValue(),'%site %id %title')
 await group.locator('[name=folderTemplate]').fill('%site\\%uploader?')
 await group.locator('[name=folderTemplate]').press('Tab')
 assert.equal(await group.locator('[name=folderTemplate]').inputValue(),'%site\\%uploader')
 await group.getByRole('button',{name:'恢复默认子文件夹格式'}).click()
 assert.equal(await group.locator('[name=folderTemplate]').inputValue(),'%site\\%title')
 await page.screenshot({path:'artifacts/download-ui-settings.png',animations:'disabled'})
 await page.locator('#settings-toggle').click()
 assert.equal(await popup.isHidden(),true)
 await page.locator('#settings-toggle').click();await page.locator('#logo').click();assert.equal(await popup.isHidden(),true)
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(700,400))
 await page.locator('#settings-toggle').click()
 const bounds=await popup.boundingBox();assert.ok(bounds.y>=0&&bounds.y+bounds.height<=400)
 await writeFile('artifacts/download-ui-metrics.json',JSON.stringify({geometry,source:expected.source},null,2))
})
